imports = [ "git.hooks" ]

[devshell]
name = "miniguest"

[[commands]]
package = "bash"

[[commands]]
package = "nixFlakes"

[[commands]]
package = "nixpkgs-fmt"
category = "formatters"

[[commands]]
package = "shfmt"
category = "formatters"

[[commands]]
package = "argbash"
category = "preprocessors"

[[commands]]
package = "shellcheck"
category = "linters"

[git.hooks]
enable = true
pre-commit.text = """
if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=$(git hash-object -t tree /dev/null)
fi

function find_staged {
  git diff-index --name-only --cached $against --diff-filter d -- "$@"
}

find_staged '*.nix' | xargs -r nixpkgs-fmt --check || exit
find_staged '*.bash' | xargs -r shfmt -d -s || exit
"""
