imports = [
  "git.hooks",
  "language.c",
  "set-boost-root.nix",
]

[devshell]
name = "miniguest"
packages = [
  "ninja", # for meson
]

[[commands]]
package = "nixFlakes"

[[commands]]
name = "task"
package = "go-task"

[[commands]]
package = "meson"

[[commands]]
package = "nixpkgs-fmt"
category = "formatters"

[[commands]]
name = "clang-format"
package = "clang-tools"
category = "formatters"

[[commands]]
name = "clang-tidy"
package = "clang-tools"
category = "linters"

[[commands]]
package = "include-what-you-use"
category = "linters"

[language.c]
includes = [
  "boehmgc",
  "nixFlakes",
  "nlohmann_json",
]

[git.hooks]
enable = true
pre-commit.text = """
if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=$(git hash-object -t tree /dev/null)
fi

function find_staged {
  git diff-index --name-only --cached $against --diff-filter d -- "$@"
}

find_staged '*.nix' | xargs -r nixpkgs-fmt --check || exit
find_staged '*.hpp' '*.cpp' | xargs -r clang-format -n -Werror || exit
"""
