imports = [ "git.hooks" ]

[devshell]
name = "miniguest"

[[commands]]
package = "nixpkgs-fmt"
category = "formatters"

[[commands]]
package = "shfmt"
category = "formatters"

[[commands]]
package = "shellcheck"
category = "linters"

[git.hooks]
enable = true
