# https://taskfile.dev

version: '3'

tasks:
  default:
    deps: [build]

  setup:
    cmds:
      - meson setup tool/ build/
    status:
      - test -d build/

  build:
    deps: [setup]
    dir: build/
    cmds:
      - meson compile

  fmt:
    deps: [fmt/nix, fmt/cpp]
  fmt/nix:
    - nixpkgs-fmt .
  fmt/cpp:
    deps: [setup]
    cmds:
      - ninja -C build/ clang-format

  lint:
    deps: [lint/cpp]
  lint/cpp:
    - ninja -C build/ clang-tidy
    - iwyu_tool.py -p=build/

  clean:
    - git clean -Xdf build/
